version: 0.2

phases:
  build:
    commands:
      - docker build -t 126735570987.dkr.ecr.eu-west-2.amazonaws.com/fubra/demo-http -f docker/web/Dockerfile .
  post_build:
    commands:
      - docker push 126735570987.dkr.ecr.eu-west-2.amazonaws.com/fubra/demo-http
