version: "3.2"

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    image: fubra/demo-http
    ports:
      - "80"
    volumes:
      - ./src:/app

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: fubra/demo-php
    env_file: dev.env
    environment:
      - MYSQL_HOST=db
    volumes:
      - ./src:/app

  db:
    image: mariadb:10.1
    env_file: dev.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
